"""PipeWire filter-chain config rendering.

Stereo EQ graph is modelled on pipewire's shipped `filter-chain/sink-eq6.conf`;
the 7.1 virtual surround stage is modelled on
`filter-chain/sink-virtual-surround-7.1-hesuvi.conf` (HeSuVi HRIR channel
mapping), with our EQ appended on both output channels.
"""
from __future__ import annotations

from typing import List

from .model import BANDS, EqSettings

NODE_PREFIX = "donglehub"
Q_PEAKING = 1.0
Q_SHELF = 0.7


def control_keys(settings: EqSettings, index: int) -> List[str]:
    """Live-control keys for band `index` (0-based) in the current mode."""
    if settings.mode == "surround":
        return [f"band{index + 1}L:Gain", f"band{index + 1}R:Gain"]
    return [f"band{index + 1}:Gain"]


def preamp_keys(settings: EqSettings) -> List[str]:
    if settings.mode == "surround":
        return ["preampL:Gain", "preampR:Gain"]
    return ["preamp:Gain"]


def _f(v: float) -> str:
    return str(float(v))


def _bq_node(name: str, band_index: int, gain: float) -> str:
    band = BANDS[band_index]
    q = Q_SHELF if band.kind != "bq_peaking" else Q_PEAKING
    return (
        "                    {\n"
        "                        type  = builtin\n"
        f"                        name  = {name}\n"
        f"                        label = {band.kind}\n"
        f'                        control = {{ "Freq" = {_f(band.freq)} "Q" = {_f(q)} "Gain" = {_f(gain)} }}\n'
        "                    }\n"
    )


def _gain_node(name: str, gain: float) -> str:
    return (
        "                    {\n"
        "                        type  = builtin\n"
        f"                        name  = {name}\n"
        "                        label = gain\n"
        f'                        control = {{ "Gain" = {_f(gain)} }}\n'
        "                    }\n"
    )


def _eq_chain(suffix: str, settings: EqSettings) -> tuple:
    """Node blocks and link lines for one channel's preamp+biquad chain.

    Returns (nodes_text, links_text, first_port, last_port).
    """
    nodes = [_gain_node(f"preamp{suffix}", settings.preamp)]
    for i, gain in enumerate(settings.gains):
        nodes.append(_bq_node(f"band{i + 1}{suffix}", i, gain))
    links = [
        f'                {{ output = "preamp{suffix}:Out" input = "band1{suffix}:In" }}\n'
    ]
    for i in range(1, len(BANDS)):
        links.append(
            f'                {{ output = "band{i}{suffix}:Out" input = "band{i + 1}{suffix}:In" }}\n'
        )
    return "".join(nodes), "".join(links), f"band1{suffix}:In", f"band{len(BANDS)}{suffix}:Out"


def _module(node_description: str, graph: str, capture: str, playback: str) -> str:
    return (
        "# Generated by donglehub — do not edit (use `donglehub eq ...`)\n"
        "context.modules = [\n"
        "    { name = libpipewire-module-filter-chain\n"
        "        args = {\n"
        f'            node.description = "{node_description}"\n'
        f'            media.name       = "{node_description}"\n'
        "            filter.graph = {\n"
        f"{graph}"
        "            }\n"
        f"{capture}"
        f"{playback}"
        "        }\n"
        "    }\n"
        "]\n"
    )


def render_eq_conf(settings: EqSettings) -> str:
    nodes, links, in_port, out_port = _eq_chain("", settings)
    graph = (
        "                nodes = [\n"
        f"{nodes}"
        "                ]\n"
        "                links = [\n"
        f"{links}"
        "                ]\n"
        f'                inputs  = [ "{in_port}" ]\n'
        f'                outputs = [ "{out_port}" ]\n'
    )
    capture = (
        "            capture.props = {\n"
        '                node.name      = "donglehub.eq"\n'
        "                media.class    = Audio/Sink\n"
        "                audio.channels = 2\n"
        "                audio.position = [ FL FR ]\n"
        "            }\n"
    )
    playback = (
        "            playback.props = {\n"
        '                node.name      = "donglehub.eq.out"\n'
        "                node.passive   = true\n"
        "                audio.channels = 2\n"
        "                audio.position = [ FL FR ]\n"
        "            }\n"
    )
    return _module("DongleHub EQ", graph, capture, playback)


# HeSuVi 14-channel HRIR mapping (from pipewire's sink-virtual-surround-7.1-hesuvi.conf):
# node: (left hrir channel, right hrir channel, gain per impulse)
_SURROUND_MAP = (
    ("convFL", 0, 1, None), ("convFR", 8, 7, None),
    ("convFC", 6, 13, 2.0), ("convLFE", 6, 13, None),
    ("convSL", 2, 3, None), ("convSR", 10, 9, None),
    ("convRL", 4, 5, None), ("convRR", 12, 11, None),
)
_MIX_LINKS = (
    ("convFL", 1), ("convSL", 2), ("convRL", 3), ("convFC", 4),
    ("convFR", 5), ("convSR", 6), ("convRR", 7), ("convLFE", 8),
)


def render_surround_conf(settings: EqSettings) -> str:
    hrir = settings.hrir
    nodes = []
    for name, ch_l, ch_r, gain in _SURROUND_MAP:
        gain_txt_l = f" gain = {_f(gain)}" if gain is not None else ""
        gain_txt_r = gain_txt_l
        nodes.append(
            f"                    {{ type = builtin label = convolver2 name = {name}\n"
            "                      config = {\n"
            "                          impulses = [\n"
            f'                            {{ filename = "{hrir}" channel = {ch_l:>{2}}{gain_txt_l} }}  # L\n'
            f'                            {{ filename = "{hrir}" channel = {ch_r:>{2}}{gain_txt_r} }}  # R\n'
            "                          ]\n"
            "                      }\n"
            "                    }\n"
        )
    nodes.append("                    { type = builtin label = mixer name = mixL }\n")
    nodes.append("                    { type = builtin label = mixer name = mixR }\n")

    l_nodes, l_links, l_in, l_out = _eq_chain("L", EqSettings(
        gains=settings.gains, preamp=settings.preamp, mode="eq",
    ))
    r_nodes, r_links, r_in, r_out = _eq_chain("R", EqSettings(
        gains=settings.gains, preamp=settings.preamp, mode="eq",
    ))

    mix_links = []
    for conv, idx in _MIX_LINKS:
        mix_links.append(f'                    {{ output = "{conv}:Out 1"  input="mixL:In {idx}" }}\n')
        mix_links.append(f'                    {{ output = "{conv}:Out 2"  input="mixR:In {idx}" }}\n')
    eq_links = [
        f'                {{ output = "mixL:Out" input = "preampL:In" }}\n',
        f'                {{ output = "mixR:Out" input = "preampR:In" }}\n',
    ]

    graph = (
        "                nodes = [\n"
        f"{''.join(nodes)}"
        f"{l_nodes}"
        f"{r_nodes}"
        "                ]\n"
        "                links = [\n"
        f"{''.join(mix_links)}"
        f"{''.join(eq_links)}"
        f"{l_links}"
        f"{r_links}"
        "                ]\n"
        '                inputs  = [ "convFL:In" "convFR:In"\n'
        '                            "convFC:In" "convLFE:In"\n'
        '                            "convRL:In" "convRR:In"\n'
        '                            "convSL:In" "convSR:In" ]\n'
        f'                outputs = [ "{l_out}" "{r_out}" ]\n'
    )
    capture = (
        "            capture.props = {\n"
        '                node.name      = "donglehub.surround"\n'
        "                media.class    = Audio/Sink\n"
        "                audio.channels = 8\n"
        "                audio.position = [ FL FR FC LFE RL RR SL SR ]\n"
        "            }\n"
    )
    playback = (
        "            playback.props = {\n"
        '                node.name      = "donglehub.surround.out"\n'
        "                node.passive   = true\n"
        "                audio.channels = 2\n"
        "                audio.position = [ FL FR ]\n"
        "            }\n"
    )
    return _module("DongleHub Surround", graph, capture, playback)


def render_conf(settings: EqSettings) -> str:
    if settings.mode == "surround":
        return render_surround_conf(settings)
    return render_eq_conf(settings)
